// <auto-generated />
using System;
using DA_LTW.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DA_LTW.Migrations
{
    [DbContext(typeof(TourDbContext))]
    partial class TourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DA_LTW.Models.Account", b =>
                {
                    b.Property<int>("sdt")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sdt");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DA_LTW.Models.Customer", b =>
                {
                    b.Property<int>("sdt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sdt"));

                    b.Property<string>("Email_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sdt");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DA_LTW.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdTour")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("sdt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTour");

                    b.HasIndex("sdt");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("DA_LTW.Models.Tour", b =>
                {
                    b.Property<int>("IdTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTour"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_tour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("People")
                        .HasColumnType("int");

                    b.Property<DateTime>("Started_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tour_guide")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTour");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("DA_LTW.Models.Account", b =>
                {
                    b.HasOne("DA_LTW.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("sdt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DA_LTW.Models.History", b =>
                {
                    b.HasOne("DA_LTW.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("IdTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA_LTW.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("sdt");

                    b.Navigation("Customer");

                    b.Navigation("Tour");
                });
#pragma warning restore 612, 618
        }
    }
}
